Replace tabs in pillar.example with spaces.
tabs cause salt to trigger a render error because tabs are 'illegal':
```
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 33, column 32:
            pid: /var/run/nginx.pid\t\t### Directory location must exist
                                   ^
```